// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5pUqmayGo4RbqdxibwvP0LNSI2feNWU',
    appId: '1:743713455907:android:0ec450a1c7ba5e775d5696',
    messagingSenderId: '743713455907',
    projectId: 'sample-app-61d66',
    storageBucket: 'sample-app-61d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfd8jpZKu5C2CgkdOjDjts5DQXz7GNSBk',
    appId: '1:743713455907:ios:09ccca580faea5e65d5696',
    messagingSenderId: '743713455907',
    projectId: 'sample-app-61d66',
    storageBucket: 'sample-app-61d66.appspot.com',
    iosClientId:
        '743713455907-q8ammi55gb80tbadlgru4667gjn9kv1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDynamicLin',
  );
}
